files:
  - source: /public/translations/fr.json
    translation: /%original_path%/%two_letters_code%.json
  - source: /public/translations/fr.json
    translation: /%original_path%/%two_letters_code%.json
